#pragma once
#include "../usfl_lib/uslf_lib.hpp"

static std::string CartridgeTypeStrings[]
{
	"ROM_ONLY",
	"MBC1",
	"MBC1_RAM",
	"MBC1_RAM_BATTERY",
	"MBC2",
	"MBC2_BATTERY",
	"ROM_RAM",
	"ROM_RAM_BATTERY",
	"MMM01",
	"MMM01_RAM",
	"MMM01_RAM_BATTERY",
	"MBC3_TIMER_BATTERY",
	"MBC3_TIMER_RAM_BATTERY",
	"MBC3",
	"MBC3_RAM",
	"MBC3_RAM_BATTERY",
	"UNKNOWN_TYPE",
	"UNKNOWN_TYPE",
	"UNKNOWN_TYPE",
	"UNKNOWN_TYPE",
	"UNKNOWN_TYPE",
	"UNKNOWN_TYPE",
	"MBC5_RAM",
	"MBC5_RAM_BATTERY",
	"MBC5_RUMBLE",
	"MBC5_RUMBLE_RAM",
	"MBC5_RUMBLE_RAM_BATTERY",
	"UNKNOWN_TYPE",
	"MBC6",
	"UNKNOWN_TYPE",
	"MBC7_SENSOR_RUMBLE_RAM_BATTERY"


};

enum CartridgeType
{
	ROM_ONLY = 0x00,
	MBC1 = 0x01,
	MBC1_RAM = 0x02,
	MBC1_RAM_BATTERY = 0x03,
	MBC2 = 0x05,
	MBC2_BATTERY = 0x06,
	ROM_RAM = 0x08,
	ROM_RAM_BATTERY = 0x09,
	MMM01 = 0x0B,
	MMM01_RAM = 0x0C,
	MMM01_RAM_BATTERY = 0x0D,
	MBC3_TIMER_BATTERY = 0x0F,
	MBC3_TIMER_RAM_BATTERY = 0x10,
	MBC3 = 0x11,
	MBC3_RAM = 0x12,
	MBC3_RAM_BATTERY = 0x13,
	UNKNOWN_TYPE_1 = 0x14,
	UNKNOWN_TYPE_2 = 0x15,
	UNKNOWN_TYPE_3 = 0x16,
	UNKNOWN_TYPE_4 = 0x17,
	UNKNOWN_TYPE_5 = 0x18,
	UNKNOWN_TYPE_6 = 0x19,
	MBC5_RAM						= 0x1A,
	MBC5_RAM_BATTERY				= 0x1B,
	MBC5_RUMBLE						= 0x1C,
	MBC5_RUMBLE_RAM					= 0x1D,
	MBC5_RUMBLE_RAM_BATTERY			= 0x1E,
	UNKNOWN_TYPE_7					= 0x1F,
	MBC6							= 0x20,
	UNKNOWN_TYPE_8					= 0x21,
	MBC7_SENSOR_RUMBLE_RAM_BATTERY  = 0x22,
	POCKET_CAMERA = 0xFC,
	BANDAI_TAMA = 0xFD,
	HUC3 = 0xFF,							

};

static std::string licensee_codes[164]
{
	"none",
	"Nintendo R & D1",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Capcom",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Electronic Arts",
	"Unknown",
	"Unknown",
	"Unknown",		
	"Unknown",
	"Hudson Soft", 	
	"b - ai",
	"kss",
	"Unknown",
	"pow",
	"Unknown",
	"PCM Complete",
	"san - x",
	"Unknown",
	"Unknown",
	"Kemco Japan",
	"seta",
	"Viacom",
	"Nintendo",
	"Bandai",
	"Ocean / Acclaim",
	"Konami",
	"Hector",			  
	"Taito",				  
	"Hudson",			  
	"Banpresto",			  
	"Unknown",			  
	"Ubi Soft", 			  
	"Atlus",				  
	"Unknown",			  
	"Malibu",			  
	"Unknown",			  
	"angel 	",			  
	"Bullet - Proof",	  
	"Unknown",			  
	"irem",				  
	"Absolute",			  
	"Acclaim",
	"Activision",
	"American sammy", 	
	"Konami",
	"Hi tech entertainment",
	"LJN",
	"Matchbox",
	"Mattel",
	"Milton Bradley", 
	"Titus",
	"Virgin",
	"Unknown",
	"Unknown",
	"LucasArts",
	"Unknown",
	"Unknown",
	"Ocean",
	"Unknown",
	"Electronic Arts",
	"Infogrames",
	"Interplay",
	"Broderbund",
	"sculptured",
	"Unknown",
	"sci",
	"Unknown",
	"Unknown",
	"THQ",
	"Accolade",
	"misawa ",
	"Unknown",
	"Unknown",
	"lozc",
	"Unknown",
	"Unknown",
	"tokuma shoten i", 
	"tsukuda ori",  
	"Unknown",
	"Unknown",
	"Unknown",
	"Chunsoft",
	"Video system", 	
	"Ocean / Acclaim",
	"Varie",
	"Yonezawas pal", 	
	"Kaneko",
	"Packin soft ",		
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"A4 Konami(Yu - Gi - Oh!)"
};
  
  
  
  
  
  
  




static std::string CartRomString[] =
{
	"0x00 - 32KByte(no ROM banking)",
	"0x01 - 64KByte(4 banks)",
	"0x02 - 128KByte(8 banks)",
	"0x03 - 256KByte(16 banks)",
	"0x04 - 512KByte(32 banks)",
	"0x05 - 1MByte(64 banks) - only 63 banks used by MBC1",
	"0x06 - 2MByte(128 banks) - only 125 banks used by MBC1",
	"0x07 - 4MByte(256 banks)",
	"0x08 - 8MByte(512 banks)",
	"0x52 - 1.1MByte(72 banks)",
	"0x53 - 1.2MByte(80 banks)",
	"0x54 - 1.5MByte(96 banks)"
};
enum CartridgeRomSize
{
	ROM_KB32NO_ROM = 0x00,
	ROM_KB64 = 0x01,
	ROM_KB128 = 0x02,
	ROM_KB256 = 0x03,
	ROM_KB512 = 0x04,
	ROM_MB1 = 0x05,
	ROM_MB2 = 0x06,
	ROM_MB4 = 0x07,
	ROM_MB8 = 0x08,
	ROM_MB1_1 = 0x52,
	ROM_MB1_2 = 0x53,
	ROM_MB1_5 = 0x54
};

static std::string CartRamString[] =
{
	"None",
	"2 KBytes",
	"8 Kbytes",
	"32 KBytes(4 banks of 8KBytes each)",
	"128 KBytes(16 banks of 8KBytes each)",
	"64 KBytes(8 banks of 8KBytes each)"
};
enum CartridgeRamSize
{
	RAM_NONE = 0x00,
	RAM_KB2 = 0x01,
	RAM_KB8 = 0x02,
	RAM_KB32 = 0x03,
	RAM_KB128 = 0x04,
	RAM_KB64 = 0x05
};

static u8 NINTENDO_LOGO[] =
{
	 0xCE, 0xED, 0x66, 0x66, 0xCC, 0x0D, 0x00, 0x0B, 0x03, 0x73, 0x00, 0x83, 0x00, 0x0C, 0x00, 0x0D,
	 0x00, 0x08, 0x11, 0x1F, 0x88, 0x89, 0x00, 0x0E, 0xDC, 0xCC, 0x6E, 0xE6, 0xDD, 0xDD, 0xD9, 0x99,
	 0xBB, 0xBB, 0x67, 0x63, 0x6E, 0x0E, 0xEC, 0xCC, 0xDD, 0xDC, 0x99, 0x9F, 0xBB, 0xB9, 0x33, 0x3E
};